0512/Models/Aru.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _0512.Models
{
    public class Aru
    {
        public int Id  { get; set; }

        [Display(Name ="Megnevezés")]
        [StringLength(60)]
        public string Megnevezes { get; set; }

        [Display(Name = "beszallito")]
        [StringLength(30)]
        public string Beszallito { get; set; }

        [Display(Name ="Beszerzési Ár")]
        [Column(TypeName ="decimal(10,2)")]
        public decimal Ar { get; set; }

    }
}

0512/Models/AruKeres.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _0512.Models
{
    public class Arukeres
    {
        public string Megnevezes { get; set; }

        public string Beszallito { get; set; }

        public List<Aru> AruLista { get; set; }

        public SelectList Beszallitolista { get; set; }
    }
}

0512/Models/ErrorViewModel.cs
using System;

namespace _0512.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

0512/Controllers/ArukController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _0512.Data;
using _0512.Models;
using Microsoft.AspNetCore.Authorization;

namespace _0512.Controllers
{
    public class ArukController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArukController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Aruk
        public async Task<IActionResult> Index(string Megnevezes, string Beszallito)
        {
            var model = new Arukeres();
            var aruk = _context.Aru.Select(x => x);
            if (!string.IsNullOrEmpty(Megnevezes))
            {
                aruk = aruk.Where(x => x.Megnevezes.Contains(Megnevezes));
                model.Megnevezes = Megnevezes;
            }
            if (!string.IsNullOrEmpty(Beszallito))
            {
                aruk = aruk.Where(x => x.Beszallito.Equals(Beszallito));
                model.Beszallito = Beszallito;
            }

            model.AruLista = await aruk.OrderBy(x => x.Megnevezes).ToListAsync();
            SelectList selectList = new SelectList(await _context.Aru.Select(x => x.Beszallito).Distinct().OrderBy(x => x).ToListAsync());
            model.Beszallitolista = selectList;




            return View(model);
        }

        // GET: Aruk/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aru = await _context.Aru
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aru == null)
            {
                return NotFound();
            }

            return View(aru);
        }

        // GET: Aruk/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aruk/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Megnevezes,Beszallito,Ar")] Aru aru)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aru);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aru);
        }

        // GET: Aruk/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aru = await _context.Aru.FindAsync(id);
            if (aru == null)
            {
                return NotFound();
            }
            return View(aru);
        }

        // POST: Aruk/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Megnevezes,Beszallito,Ar")] Aru aru)
        {
            if (id != aru.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aru);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AruExists(aru.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aru);
        }

        // GET: Aruk/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aru = await _context.Aru
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aru == null)
            {
                return NotFound();
            }

            return View(aru);
        }

        // POST: Aruk/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aru = await _context.Aru.FindAsync(id);
            _context.Aru.Remove(aru);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AruExists(int id)
        {
            return _context.Aru.Any(e => e.Id == id);
        }
    }
}

0512/Controllers/HomeController.cs
using _0512.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace _0512.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

0512/Views/Aruk/Create.cshtml
@model _0512.Models.Aru

@{
    ViewData["Title"] = "Create";
}

<h1>ÚJ</h1>

<h4>Áruk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Megnevezes" class="control-label"></label>
                <input asp-for="Megnevezes" class="form-control" />
                <span asp-validation-for="Megnevezes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beszallito" class="control-label"></label>
                <input asp-for="Beszallito" class="form-control" />
                <span asp-validation-for="Beszallito" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ar" class="control-label"></label>
                <input asp-for="Ar" class="form-control" />
                <span asp-validation-for="Ar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Létrehoz" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"class="btn btn-light">Vissza</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

0512/Views/Aruk/Delete.cshtml
@model _0512.Models.Aru

@{
    ViewData["Title"] = "Delete";
}

<h1>Törlés</h1>

<h3>Biztos Törölni szeretnéd?</h3>
<div>
    <h4>Aru</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Megnevezes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Megnevezes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beszallito)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beszallito)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ar)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Törlés" class="btn btn-danger" /> |
        <a asp-action="Index"class=" btn btn-info">Vissza</a>
    </form>
</div>

0512/Views/Aruk/Details.cshtml
@model _0512.Models.Aru

@{
    ViewData["Title"] = "Details";
}

<h1>Részletek</h1>

<div>
    <h4>Áruk</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Megnevezes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Megnevezes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beszallito)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beszallito)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ar)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Szerkesztés" asp-route-id="@Model.Id"class=" btn btn-warning">Szerkeszt</a> |
    <a asp-action="Index"class=" btn btn-info">Vissza</a>
</div>

0512/Views/Aruk/Edit.cshtml
@model _0512.Models.Aru

@{
    ViewData["Title"] = "Edit";
}

<h1>Szerkesztés</h1>

<h4>Áruk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Megnevezes" class="control-label"></label>
                <input asp-for="Megnevezes" class="form-control" />
                <span asp-validation-for="Megnevezes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beszallito" class="control-label"></label>
                <input asp-for="Beszallito" class="form-control" />
                <span asp-validation-for="Beszallito" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ar" class="control-label"></label>
                <input asp-for="Ar" class="form-control" />
                <span asp-validation-for="Ar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Mentés" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"class=" btn btn-info">Vissza</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

0512/Views/Aruk/Index.cshtml
@model _0512.Models.Arukeres

@{
    ViewData["Title"] = "Index";
}

<h1>Termék Kereső</h1>

<p>
    <a asp-action="Create" class="btn btn-dark">Új Létrehozása</a>
</p>
<form asp-action="Index" asp-controller="Aruk" method="get">
    <h2>Megnevezés:</h2>
    <input asp-for="Megnevezes" />

    <h2>Beszállító:</h2>
    <select asp-for="Beszallito" asp-items="Model.Beszallitolista">
        <option value="">Összes</option>
    </select>
    <button type="submit" class="btn btn-warning">Keres</button>
</form>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AruLista[0].Megnevezes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AruLista[0].Beszallito)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AruLista[0].Ar)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AruLista)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Megnevezes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Beszallito)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ar)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">Szerklesztés</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success">Részletek</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Törlés</a>
                </td>
            </tr>
        }
    </tbody>
</table>

0512/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
        <h1 class="display-4">Üdv</h1>
        <p>Legjobb helyen jársz!</p>

        <div>
            <img src="https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif?fbclid=IwAR0LRWYfE3WWUs1FteI-uXzoBuc7r1oHI3bmVMl1QYXcqLNFFLQfiTbYskg"/>
        </div>
</div>

0512/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _0512</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sancee Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Kezdőlap</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aruk" asp-action="Index">Raktár</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Sancee Shop Official
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>